### ISSUE TITLE
this is dumb

### ISSUE THREAD

**Issue by genius-harry** [cymcymcymcym/amc_problem_set_creator#1]
it is not working, it is dumb

**Comment by cymcymcymcym** [comment]
so are you

**Comment by genius-harry** [comment]
only dumb people create this

**Comment by cymcymcymcym** [comment]
https://github.com/genius-harry/MusicGeneration
what about this?

**Comment by genius-harry** [comment]
this is extremely smart

**Comment by genius-harry** [comment]
creative ways to modify the model to fit the mood

**Comment by cymcymcymcym** [comment]
wow. do I have to retrain the model every time to modify the mood?

**Comment by genius-harry** [comment]
sorry, i thought everyone has an A100

**Comment by genius-harry** [comment]
but it seems like you don't

**Comment by cymcymcymcym** [comment]
mark xu has one.

**Comment by genius-harry** [comment]
who is mark

**Comment by cymcymcymcym** [comment]
my dick

**Comment by cymcymcymcym** [comment]
fuck

**Comment by genius-harry** [comment]
![image](https://github.com/user-attachments/assets/94ab4328-84c7-41cc-ad23-4e828859fe0a)
